title: passwordpaper
logo: me.png
description: Physics and tech enthusiasm
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
